#!/usr/bin/env python3
"""Convert the four VelaCare 16 kHz mono WAV prompts into a PROGMEM header."""

from __future__ import annotations

import argparse
import pathlib
import struct
import wave


PROMPTS = (
    ("fall", "kVoiceFallClip", "\u68c0\u6d4b\u5230\u7591\u4f3c\u8dcc\u5012\uff0c\u8bf7\u95ee\u60a8\u8fd8\u597d\u5417\uff1f"),
    ("persistent", "kVoicePersistentClip", "\u6682\u672a\u6536\u5230\u56de\u5e94\uff0c\u6b63\u5728\u901a\u77e5\u5bb6\u4eba\u3002"),
    ("family", "kVoiceFamilyClip", "\u5bb6\u4eba\u5df2\u7ecf\u6536\u5230\u6d88\u606f\uff0c\u8bf7\u4e0d\u8981\u7740\u6025\u3002"),
    ("elder", "kVoiceElderClip", "\u597d\u7684\uff0c\u5df2\u7ecf\u5411\u5bb6\u4eba\u62a5\u544a\u60a8\u76ee\u524d\u5b89\u5168\u3002"),
)

SAMPLE_RATE = 16_000
SILENCE_THRESHOLD = 240
PRE_ROLL_SAMPLES = 80 * SAMPLE_RATE // 1000
POST_ROLL_SAMPLES = 180 * SAMPLE_RATE // 1000
FADE_SAMPLES = 12 * SAMPLE_RATE // 1000
TARGET_PEAK = 9_000


def read_and_prepare(path: pathlib.Path) -> list[int]:
    with wave.open(str(path), "rb") as wav:
        if (
            wav.getnchannels() != 1
            or wav.getsampwidth() != 2
            or wav.getframerate() != SAMPLE_RATE
        ):
            raise ValueError(f"{path} must be 16 kHz, 16-bit, mono PCM")
        raw = wav.readframes(wav.getnframes())

    samples = list(struct.unpack(f"<{len(raw) // 2}h", raw))
    start = 0
    end = len(samples)
    while start < end and abs(samples[start]) < SILENCE_THRESHOLD:
        start += 1
    while end > start and abs(samples[end - 1]) < SILENCE_THRESHOLD:
        end -= 1
    samples = samples[start:end]
    if not samples:
        raise ValueError(f"{path} contains no audible samples")

    peak = max(abs(sample) for sample in samples)
    if peak > TARGET_PEAK:
        scale = TARGET_PEAK / peak
        samples = [int(round(sample * scale)) for sample in samples]

    fade_count = min(FADE_SAMPLES, len(samples) // 2)
    for index in range(fade_count):
        gain = (index + 1) / fade_count
        samples[index] = int(round(samples[index] * gain))
        samples[-1 - index] = int(round(samples[-1 - index] * gain))

    return [0] * PRE_ROLL_SAMPLES + samples + [0] * POST_ROLL_SAMPLES


def array_name(clip_name: str) -> str:
    return clip_name.removesuffix("Clip") + "Pcm"


def render_header(clips: list[tuple[str, str, str, list[int]]]) -> str:
    lines = [
        "// Generated by tools/wav_to_voice_header.py. Do not edit by hand.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "struct VoicePromptClip {",
        "  const int16_t *samples;",
        "  uint32_t sampleCount;",
        "  const char *name;",
        "};",
        "",
    ]
    for source_name, clip_name, phrase, samples in clips:
        pcm_name = array_name(clip_name)
        lines.append(f"// {source_name}: {phrase}")
        lines.append(f"static const int16_t {pcm_name}[] PROGMEM = {{")
        for offset in range(0, len(samples), 16):
            row = ", ".join(f"{value:6d}" for value in samples[offset : offset + 16])
            lines.append(f"  {row},")
        lines.extend(
            [
                "};",
                f"static constexpr VoicePromptClip {clip_name} = {{",
                f"    {pcm_name},",
                f"    static_cast<uint32_t>(sizeof({pcm_name}) / sizeof({pcm_name}[0])),",
                f'    "{source_name}",',
                "};",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()

    clips: list[tuple[str, str, str, list[int]]] = []
    for source_name, clip_name, phrase in PROMPTS:
        samples = read_and_prepare(args.input_dir / f"{source_name}.wav")
        clips.append((source_name, clip_name, phrase, samples))
        print(
            f"{source_name}: {len(samples)} samples, "
            f"{len(samples) / SAMPLE_RATE:.2f}s, {len(samples) * 2} bytes"
        )

    args.output.write_text(render_header(clips), encoding="utf-8", newline="\n")
    print(f"Wrote {args.output} ({args.output.stat().st_size} source bytes)")


if __name__ == "__main__":
    main()
