#ifndef __NUTTX_CONFIG_H
#define __NUTTX_CONFIG_H

#define FAR

#define CONFIG_VELACARE_ENABLE_AGENT
#define CONFIG_VELACARE_DATA_DIR "/data/velacare"
#define CONFIG_VELACARE_SIM_SENSOR 1
#define CONFIG_VELACARE_POLL_MS 5000
#define CONFIG_VELACARE_ALARM_NODE ""
#define CONFIG_LIBC_LOCALTIME

#define CONFIG_LV_FONT_SIMSUN_16_CJK
#define CONFIG_LV_FONT_MONTSERRAT_28
#define CONFIG_LV_FONT_MONTSERRAT_24

#endif
